# Generated by Django 6.0 on 2025-12-19 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakebuilder', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_booking', to='cakebuilder.order'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('11:00', '11:00 AM'), ('13:00', '1:00 PM'), ('15:00', '3:00 PM'), ('17:00', '5:00 PM')], max_length=5),
        ),
    ]
